/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

/**
 *
 * @author anmol singh sethi
 */
public class adminhome extends javax.swing.JFrame {

    /**
     * Creates new form adminhome
     */
    String username;
    public adminhome( String username) {
        initComponents();
        setSize(800, 800);
        this.username=username;
        lbwel.setText("welcome "+username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbwel = new javax.swing.JLabel();
        btchangepass = new javax.swing.JButton();
        btdtd = new javax.swing.JButton();
        btviewdept = new javax.swing.JButton();
        btcourses = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        btaddsub = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lbwel.setText("Welcome");
        getContentPane().add(lbwel);
        lbwel.setBounds(150, 10, 190, 70);

        btchangepass.setText("Change Password");
        btchangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchangepassActionPerformed(evt);
            }
        });
        getContentPane().add(btchangepass);
        btchangepass.setBounds(100, 80, 170, 25);

        btdtd.setText("Add Department");
        btdtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdtdActionPerformed(evt);
            }
        });
        getContentPane().add(btdtd);
        btdtd.setBounds(100, 130, 170, 30);

        btviewdept.setText("View Departments");
        btviewdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewdeptActionPerformed(evt);
            }
        });
        getContentPane().add(btviewdept);
        btviewdept.setBounds(100, 190, 170, 30);

        btcourses.setText("Add Courses");
        btcourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcoursesActionPerformed(evt);
            }
        });
        getContentPane().add(btcourses);
        btcourses.setBounds(100, 250, 170, 30);

        btview.setText("View all courses");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });
        getContentPane().add(btview);
        btview.setBounds(100, 310, 170, 30);

        btaddsub.setText("Add Subject");
        btaddsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddsubActionPerformed(evt);
            }
        });
        getContentPane().add(btaddsub);
        btaddsub.setBounds(110, 380, 150, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btchangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchangepassActionPerformed
        newpassword np=new newpassword(username);
        np.setVisible(true);
        
    }//GEN-LAST:event_btchangepassActionPerformed

    private void btdtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdtdActionPerformed
        add_dept newdept=new add_dept();
        newdept.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btdtdActionPerformed

    private void btviewdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewdeptActionPerformed
        Viewdepartments vd = new Viewdepartments();
        vd.setVisible(true);
        
    }//GEN-LAST:event_btviewdeptActionPerformed

    private void btcoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcoursesActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
      Viewcourses vc= new Viewcourses();
      vc.setVisible(true);
     
    }//GEN-LAST:event_btviewActionPerformed

    private void btaddsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddsubActionPerformed
        addsubject as=new addsubject();
        as.setVisible(true);
        as.setSize(500, 600);
        // TODO add your handling code here:
    }//GEN-LAST:event_btaddsubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                adh.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaddsub;
    private javax.swing.JButton btchangepass;
    private javax.swing.JButton btcourses;
    private javax.swing.JButton btdtd;
    private javax.swing.JButton btview;
    private javax.swing.JButton btviewdept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbwel;
    // End of variables declaration//GEN-END:variables
}
